spring:
  application:
    name: Order-service

  datasource:
    url: jdbc:mysql://localhost:3306/scs?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Ijse@123
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update


      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true

  main:
    allow-bean-definition-overriding: true

jwt:
  secret: 2D4A614E645267556B58703273357638792F423F4428472B4B6250655368566DF423F4428472B4B6250655368566D
  expiration: 3600000

server:
  port: 8081